### ISSUE TITLE
Add float data type

### ISSUE THREAD

**Issue by valentinomariotto** [Zoha/laravel-meta#30]
**Feature request**

Hi! Thank you for this awesome package, it's really useful.
It'd be great if you could add support for the float data type.
Thank you

**Comment by Zoha** [comment]
hi @valentinomariotto 
thank you for your suggestion 
I'll consider this for the next version

**Comment by XGhozt** [comment]
This is actually a bug and needs to be fixed because it can result in unexpected behavior when setting meta data.

For example, if you do `$model->setMeta('price', 12.34);` then it will save the value as "12.34" but set the type as "integer". It's only when using `$model->getMeta('price')` do you suddenly only get "12" returned despite the value being saved into the database with the decimal. Of course you can pass "float" as the type when setting the meta. But this leads to unexpected behavior when we assume setMeta will correctly detect the value type.

**Comment by Zoha** [comment]
thanks @XGhozt for reporting 
I'll take a look at it

**Comment by XGhozt** [comment]
> thanks @XGhozt for reporting I'll take a look at it

Sweet! If I get some time, I can submit a PR this month but I imagine it's quite a simple patch.

**Comment by Zoha** [comment]
@XGhozt it would be great if you could raise a patch PR
please let me know if you can work on it

**Comment by XGhozt** [comment]
I've just added the PR. I also updated the tests but I have not worked on this package before so let me know if I missed anything, but it seems to be working for me.

**Comment by Zoha** [comment]
added #32
